# 0. PyTorch import 확인

In [1]:
import torch

print(torch.__version__)

2.5.1


# 1. 텐서 생성

In [ ]:
# 1D(스칼라) 텐서 생성
tensor_1d = torch.tensor([1, 2, 3, 4, 5, 6])
print("1D Tensor:\n", tensor_1d)

# 2D(행렬) 텐서 생성
tensor_2d = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("\n\n2D Tensor:\n", tensor_2d)

# 3D 텐서 생성
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n\n3D Tensor:\n", tensor_3d)


In [ ]:
# 텐서의 차원 확인
print("\n1D Tensor Dimension:", tensor_1d.dim())
print("2D Tensor Dimension:", tensor_2d.dim())
print("3D Tensor Dimension:", tensor_3d.dim())

# 텐서의 크기 확인
print("\n1D Tensor Size:", tensor_1d.size())
print("2D Tensor Size:", tensor_2d.size())
print("3D Tensor Size:", tensor_3d.size())

# 텐서의 데이터 타입 확인
print("\n1D Tensor Data Type:", tensor_1d.dtype)
print("2D Tensor Data Type:", tensor_2d.dtype)
print("3D Tensor Data Type:", tensor_3d.dtype)

In [ ]:
# 0으로 채워진 텐서 생성
zero_tensor = torch.zeros((2, 3))
print("Zero Tensor:\n", zero_tensor)

# 1로 채워진 텐서 생성
one_tensor = torch.ones((3, 2))
print("\n\nOne Tensor:\n", one_tensor)

# 랜덤 값으로 채워진 텐서 생성
random_tensor = torch.rand((2, 2))
print("\n\nRandom Tensor:\n", random_tensor)

# 2. 텐서 연산

In [2]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print("x+y:\n", x + y)
print("x*y:\n", x * y)
print("x@y:\n", torch.matmul(x, y))
print("x.T:\n", x.T)  # 전치

x+y:
 tensor([[ 6.,  8.],
        [10., 12.]])
x*y:
 tensor([[ 5., 12.],
        [21., 32.]])
x@y:
 tensor([[19., 22.],
        [43., 50.]])
x.T:
 tensor([[1., 3.],
        [2., 4.]])


# 3. 텐서 변환(Numpy <-> Tensor)
&nbsp; *메모리는 공유되서 변환한 텐서를 고치면 기존것도 바뀜 -> 꼭 필요하면 clone() 사용

In [ ]:
import numpy as np


# Numpy 배열을 PyTorch 텐서로 변환
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_np = torch.from_numpy(np_array)
print("Tensor from Numpy:\n", tensor_from_np)


# PyTorch 텐서를 Numpy 배열로 변환
tensor = torch.tensor([[7, 8, 9], [10, 11, 12]])
np_from_tensor = tensor.numpy()
print("\n\nNumpy from Tensor:\n", np_from_tensor)

In [ ]:
# 변환한 텐서 수정
tensor_from_np[0, 0] = 99
print("\nModified Tensor from Numpy:\n", tensor_from_np)
print("\n\nOriginal Numpy Array after Tensor Modification:\n", np_array)

In [ ]:
# 해결법: clone() 사용
tensor_from_np_clone = torch.from_numpy(np_array).clone()
tensor_from_np_clone[0, 0] = 88
print("\nCloned Tensor from Numpy:\n", tensor_from_np_clone)
print("\nOriginal Numpy Array after Cloned Tensor Modification:\n", np_array)

# 4. GPU 사용

In [10]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.rand((2, 2))
x = x.to(device)
print(x.device)

cpu
